parameters:
    tabernicola_juke_cloud.datadir: /datos/Music/
    tabernicola_juke_cloud.covers_dir: %tabernicola_juke_cloud.datadir%covers
services:
#    tabernicola_juke_cloud.example:
#        class: %tabernicola_juke_cloud.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
