parameters:
    tabernicola_juke_cloud.datadir: /datos/Music/
    
services:
#    tabernicola_juke_cloud.example:
#        class: %tabernicola_juke_cloud.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
