Tabernicola\JukeCloudBundle\Entity\Song:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [title, artist, disk]
            message: 'Esta canción ya existe en la libreria'
    properties:
        file:
            - File:
                maxSize: 15M
                mimeTypesMessage: Please upload a valid Song
        title:
            - NotBlank: ~
        disk:
            - NotNull: ~
        artist:
            - NotNull: ~
        number:
            - Range:
                min: 1
                max: 999