Tabernicola\JukeCloudBundle\Entity\Song:
    properties:
        file:
            - File:
                maxSize: 15M
                mimeTypesMessage: Please upload a valid Song
        title:
            - NotBlank: ~
        disk:
            - NotNull: ~
        artist:
            - NotNull: ~
        number:
            - Range:
                min: 1
                max: 999