Tabernicola\JukeCloudBundle\Entity\Disk:
    type: entity
    table: Disk
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        cover:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        slug:
            type: string
            length: 255
            gedmo:
                slug:
                    separator: "-"
                    fields:
                        - title
                    unique: false
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        artist:
            targetEntity: Artist
            inversedBy: disks
    oneToMany:
        songs:
            targetEntity: Song
            mappedBy: disk
    lifecycleCallbacks: {  }
    repositoryClass: Tabernicola\JukeCloudBundle\Entity\DiskRepository
