parameters:
#    tabernicola_juke_cloud_admin.example.class: Tabernicola\JukeCloudAdminBundle\Example

services:
#    tabernicola_juke_cloud_admin.example:
#        class: %tabernicola_juke_cloud_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
