<?php

namespace Tabernicola\JukeCloudBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiskRepository extends EntityRepository
{
    public function search($q){
        $qb = $this->createQueryBuilder('d');

        $qb->select('d')
            ->where('d.title LIKE :q')
            ->addorderBy('d.title','ASC')
            ->setParameter('q', "%$q%");
        return $qb->getQuery()->getResult();
    }
}
