<?php

namespace Tabernicola\JukeCloudBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiskRepository extends EntityRepository
{
}
