<?php

namespace Tabernicola\JukeCloudBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;
/**
 * SongRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SongRepository extends EntityRepository
{
    public function search($q){
        $qb = $this->createQueryBuilder('s');

        $qb->select('s')
            ->where('s.title LIKE :q')
            ->addorderBy('s.number','ASC')
            ->setParameter('q', "%$q%");
        return $qb->getQuery()->getResult();
    }
}
